### ISSUE TITLE
Extra bracket in sql code

### ISSUE THREAD

**Issue by marek05** [ohdsi-studies/PioneerWatchfulWaiting#10]
I run the package v0.2.0 and got some issues with running sql files. We are using postgresql. 

SQL file 103.sql has extra bracket in DATEADD(day,180,start_date)**)**

https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/f860839614c129f73a41c54a3a1e11e9b6959686/inst/sql/sql_server/103.sql#L964

Similar issues with 104.sql, 106.sql, 108.sql, 110.sql, 111.sql, 112.sql
https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/f860839614c129f73a41c54a3a1e11e9b6959686/inst/sql/sql_server/104.sql#L1001

https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/f860839614c129f73a41c54a3a1e11e9b6959686/inst/sql/sql_server/106.sql#L1211

https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/f860839614c129f73a41c54a3a1e11e9b6959686/inst/sql/sql_server/108.sql#L1389

https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/f860839614c129f73a41c54a3a1e11e9b6959686/inst/sql/sql_server/110.sql#L1424

https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/f860839614c129f73a41c54a3a1e11e9b6959686/inst/sql/sql_server/111.sql#L964

https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/f860839614c129f73a41c54a3a1e11e9b6959686/inst/sql/sql_server/112.sql#L1001

**Comment by keesvanbochove** [comment]
Hi, what database system are you using?

**Comment by marek05** [comment]
We are using Postgresql 12.4

**Comment by keesvanbochove** [comment]
Could you verify if it works with the current master version (`devtools::install_github("ohdsi-studies/PioneerWatchfulWaiting"`)?

**Comment by scossin** [comment]
Same problem in Oracle, I'll re-install the latest version and try again.
