### ISSUE TITLE
Error in km_raw %>% dplyr::mutate(timeToEvent = as.integer(as.Date(eventDate) -  :    could not find function "%>%"

### ISSUE THREAD

**Issue by scossin** [ohdsi-studies/PioneerWatchfulWaiting#13]
The error happens when running the "runStudy" function. Adding library(dplyr) beforing running the function solved the issue for us.

**Comment by keesvanbochove** [comment]
By adding dplyr and magrittr to the package dependencies, this should be fixed now.
