### ISSUE TITLE
Missing column names filled in: 'X1'

### ISSUE THREAD

**Issue by scossin** [ohdsi-studies/PioneerWatchfulWaiting#2]
We have executed the package, we had no error but a warning message at the end of the execution:

Warning message:
Missing column names filled in: 'X1' [1]

The CSV output file is correct, 3 headers, 3 columns. Some SQL queries returned 0 result so we have only 5 rows, I don't know if it could be related to this warning.

**Comment by keesvanbochove** [comment]
This issue is obsolete, now that we have removed the cohort counting code and added cohort diagnostics and study execution instead.
