### ISSUE TITLE
Remove stats generation from sql 

### ISSUE THREAD

**Issue by MaximMoinat** [ohdsi-studies/PioneerWatchfulWaiting#23]
@Tsemharb The new sql files include stats generation. This requires specification of the @results_database_schema, which we currently do not do. This is easily fixed by using [`ROhdsiWebApi::insertCohortDefinitionInPackage()`](https://ohdsi.github.io/ROhdsiWebApi/reference/insertCohortDefinitionInPackage.html) with `generateStats = FALSE`. 

See also this code: https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/master/extras/update_cohort_definitions.R

**Comment by keesvanbochove** [comment]
Closed by reverting latest commits to v0.3.2
