### ISSUE TITLE
Error Cohort 47 when using runStudy function

### ISSUE THREAD

**Issue by rfherrerac** [ohdsi-studies/PioneerWatchfulWaiting#25]
errorReportSQL:

DBMS:
redshift

Error:
java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "@" 
Position: 13;

SQL:
delete from @results_database_schema.cohort_inclusion_result where cohort_definition_id = 47 and mode_id = 0

R version:
R version 4.0.3 (2020-10-10)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- PioneerWatchfulWaiting (0.3.2)
- DatabaseConnector (4.0.0)

**Comment by rfherrerac** [comment]
Is it related to #23?

**Comment by MaximMoinat** [comment]
@rfherrerac Yes, that is indeed the same issue. I have to check with @Tsemharb to see how we can best fix this. Please revert to release 2.3 for now.

**Comment by keesvanbochove** [comment]
@rfherrerac is this with released version 0.3.2 or with the master branch?

**Comment by keesvanbochove** [comment]
Closed by reverting latest commits to v0.3.2
