### ISSUE TITLE
Error when running cohortDiagnostics

### ISSUE THREAD

**Issue by YorgosA** [ohdsi-studies/PioneerWatchfulWaiting#27]
I run the first part of the package (cohortDiagnostics) and after running for almost 42 hours it finished with an error and didn't produce the expected output. I'm pasting the last rows of the cohortDiagnosticslog.txt file below:

Finding orphan concepts took 4.45 mins
Running concept set diagnostics took 4.43 hours
Creating time distributions
Error when running CohortDiagnostics::runCohortDiagnostics on CohortGroup: target
Error in FALSE: Error executing SQL:
**java.sql.SQLException: [Amazon] (500310) Invalid operation: syntax error at or near ","** 
Position: 93;
An error report has been created at  /home/gargyriou/Packages/pioneer_031/PioneerWatchfulWaiting-0.3.1/errorReportSql.txt

Run Cohort Diagnostics started at 2021-04-09 13:29:30
Created folder at /home/gargyriou/output/pioneer_v2//OpenClaims/diagnostics/outcome
Number of cohorts 10
Found existing record keeping file in incremental folder - CreatedDiagnostics.csv
Saving database metadata
Saving database metadata took 0.0268 secs
Error when running CohortDiagnostics::runCohortDiagnostics on CohortGroup: outcome
Error in FALSE: Error executing SQL:
java.sql.SQLException: [Amazon] (500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
An error report has been created at  /home/gargyriou/Packages/pioneer_031/PioneerWatchfulWaiting-0.3.1/errorReportSql.txt

Run Cohort Diagnostics started at 2021-04-09 13:29:35
Created folder at /home/gargyriou/output/pioneer_v2//OpenClaims/diagnostics/strata
Number of cohorts 38
Found existing record keeping file in incremental folder - CreatedDiagnostics.csv
Saving database metadata
Saving database metadata took 0.0282 secs
Error when running CohortDiagnostics::runCohortDiagnostics on CohortGroup: strata
Error in FALSE: Error executing SQL:
java.sql.SQLException: [Amazon] (500310) Invalid operation: current transaction is aborted, commands ignored until end of transaction block;
An error report has been created at  /home/gargyriou/Packages/pioneer_031/PioneerWatchfulWaiting-0.3.1/errorReportSql.txt

I think the issue will be in the first error message. The two other errors are consequence of the first one.

**Comment by keesvanbochove** [comment]
Hello @YorgosA could you also include (last part of) cohortDiagnosticsLog.txt? This should show which cohort definition is the culprit.

**Comment by keesvanbochove** [comment]
Hello @YorgosA looking at this log and the timing I think you actually ran v0.3.1 which had some known errors. Could you try installing and running version 0.3.2 instead?

**Comment by YorgosA** [comment]
Sure. I'll let you know once it is done.

**Comment by YorgosA** [comment]
The error comes up when the package is trying to create time distributions. 

From the console:

_Finding orphan concepts took 12.6 mins
Running concept set diagnostics took 5.28 hours
Creating time distributions
Error when running CohortDiagnostics::runCohortDiagnostics on CohortGroup: strata
Error in FALSE: Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "," 
Position: 93;
An error report has been created at  /home/gargyriou/Packages/pioneer_032/PioneerWatchfulWaiting-0.3.2/errorReportSql.txt_

In the errorReportSql.txt file:

_SQL:
SELECT COUNT(*) FROM study_reference.PIONEER_OpenClaims_stg WHERE cohort_definition_id = 304,313,319,327,328,329,330,331,332,333,337,338_ 

The code above needs **in** and brackets for multiple values, not equal sign.
I cannot find the SQL file in the package to fix it. Can you help?

**Comment by keesvanbochove** [comment]
@YorgosA which versions of the CohortDiagnostics and FeatureExtraction packages do you have installed, and do these match the ones in renv.lock? This could should be invoked from R/TimeDistributions.R.  Could you try ensuring that FeatureExtraction v3.1.0 is installed? Looking at https://github.com/OHDSI/FeatureExtraction/compare/v3.0.1...v3.1.0 this may have been fixed in that version (R/GetCovariates.R).

**Comment by YorgosA** [comment]
I had FeatureExtraction v3.0.1 as renv suggested. Switching to FeatureExtraction v3.1.0 fixed the problem however so you can update renv.lock.
