### ISSUE TITLE
Errors when connecting to the SQL server with DatabaseConnector

### ISSUE THREAD

**Issue by velvinnn** [ohdsi-studies/PioneerWatchfulWaiting#35]
Hi there, I have an error when trying to connect to the MS sql server with the following code:

dbms = Sys.getenv("DBMS")
##I also tried with dll with 32-bit system, but the error still occurs.
Sys.setenv("PATH_TO_AUTH_DLL" = "C:/Users/xxx/Documents/JDBC/sqljdbc_6.0/enu/auth/x64")
server = Sys.getenv("DB_SERVER")
pathToDriver <- if (Sys.getenv("PATH_TO_DRIVER") == "") NULL else Sys.getenv("PATH_TO_DRIVER")
library(DatabaseConnector)
connectionDetails <- createConnectionDetails(dbms = dbms,
                                                                server = server,
                                                                pathToDriver = pathToDriver)
conn <- connect(connectionDetails)

I got the following error message and it traces back like this:

**> conn <- connect(connection details)**
Connecting using SQL Server driver using Windows integrated security
Looking for authentication DLL in path specified in PATH_TO_AUTH_DLL: C:/Users/xxx/Documents/JDBC/sqljdbc_6.0/enu/auth/x64
Error in rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect",  : 
  com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:xxx
**> traceback()**
6: stop(structure(list(message = "com.microsoft.sqlserver.jdbc.SQLServerException: This driver is not configured for integrated authentication. ClientConnectionId:xxx", 
       call = rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", 
           "connect", as.character(url), p), jobj = new("jobjRef", 
           jobj = <pointer: xxx>, jclass = "com/microsoft/sqlserver/jdbc/SQLServerException")), class = c("SQLServerException", 
   "SQLException", "Exception", "Throwable", "Object", "error", 
   "condition")))
5: .jcheck(silent = FALSE)
4: rJava::.jcall(jdbcDriver, "Ljava/sql/Connection;", "connect", 
       as.character(url), p)
3: connectUsingJdbcDriver(driver, connectionString, dbms = dbms)
2: connect(dbms = connectionDetails$dbms, user = connectionDetails$user(), 
       password = connectionDetails$password(), server = connectionDetails$server(), 
       port = connectionDetails$port(), extraSettings = connectionDetails$extraSettings, 
       oracleDriver = connectionDetails$oracleDriver, connectionString = connectionDetails$connectionString(), 
       pathToDriver = connectionDetails$pathToDriver)
1: connect(connectionDetails)
>

Thanks in advance for your help!

**Comment by scossin** [comment]
According to [this stackoverflow post](https://stackoverflow.com/questions/6087819/jdbc-sqlserverexception-this-driver-is-not-configured-for-integrated-authentic), the error "this driver is not configured for integrated authentication" is caused by a missing **sqljdbc_auth.dll** in the system path.   
Stackoverflow user Pavan suggests downloading this file from Microsoft site and put it in the Java/jre7/bin and Java/jre7/lib folder for rJava to find it.
