### ISSUE TITLE
Time to event tab shows an empty plot

### ISSUE THREAD

**Issue by MaximMoinat** [ohdsi-studies/PioneerWatchfulWaiting#38]
![image](https://user-images.githubusercontent.com/17825660/120189189-50c42400-c217-11eb-8af8-e73b39c6058d.png)

Originally reported by Bertrand #34 .

**Comment by bdemeulder** [comment]
With the version from the master branch locally, I get the following: 
![shiny app time to event 02062021](https://user-images.githubusercontent.com/11734167/120506805-8c512080-c3c6-11eb-8298-781e025efebe.png)

**Comment by MaximMoinat** [comment]
I am trying to find out what the issue is. So far, what I found is that the `cohortTimeToEvent` object in the PreMerged data contains the columns: 
![image](https://user-images.githubusercontent.com/17825660/120521200-f7095880-c3d4-11eb-8215-6a4f02732962.png)

while the code tries to subset columns n.censor and n.risk
https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/3b8257e5f45028a505d93cfc048a84a656f66a58/inst/shiny/PioneerWatchfulWaitingExplorer/server.R#L321

@Tsemharb Any idea? Do we expect that the study results contain these columns?

**Comment by MaximMoinat** [comment]
Same for the newest results (Task 4). There seem to be columns missing from the `cohortTimeToEvent` variable.
@Tsemharb Could you comment?

**Comment by bdemeulder** [comment]
I guess we can close this as the new version does include the proper fields?
