### ISSUE TITLE
Update app on ShinyDeploy

### ISSUE THREAD

**Issue by MaximMoinat** [ohdsi-studies/PioneerWatchfulWaiting#39]
The last update of [the PIONEER WatchfulWaiting shiny app on ShinyDeploy](https://github.com/OHDSI/ShinyDeploy/tree/master/PioneerWatchfulWaitingDiag) was over two months ago. We should update the code there to fix some issues with the currently deployed app (see #34).

Do we want to do an intermediate update or wait for fixing the time to event plot #38?

**Comment by MaximMoinat** [comment]
And who are authorised to do these updates? I know at least @keesvanbochove and @Anne0507 have access (and I do not).

**Comment by bdemeulder** [comment]
I can commit the changes over to the ShinyDeploy server. It sometimes takes a while for someone at OHDSI to accept it.

**Comment by keesvanbochove** [comment]
Right @MaximMoinat I don't have push rights either (nor does Anne) but you
can always open a PR to OHDSI/ShinyDeploy.

**Comment by bdemeulder** [comment]
Just updated the cohort.csv file.

**Comment by bdemeulder** [comment]
The cohort tab now shows the right list of cohorts. I still get the following in the compare cohort characteristics tab
![Shiny app 02062021](https://user-images.githubusercontent.com/11734167/120507039-c3bfcd00-c3c6-11eb-8260-06b66fd59e38.png)

**Comment by MaximMoinat** [comment]
I cannot replicate this issue on the current master branch. For me it displays the cohort names nicely. It used to work for me as well without the cohort.csv updates.
![image](https://user-images.githubusercontent.com/17825660/120519182-a2fd7480-c3d2-11eb-97e6-323a02733e56.png)

**Comment by bdemeulder** [comment]
@MaximMoinat  I've downloaded the master branch again and I still get the same issue. 

Which data are you using?

**Comment by MaximMoinat** [comment]
I am using the following file in Teams:
`Cohort testing -> Task #3 Second version of package -> Results ->
Premerged.RData`

**Comment by bdemeulder** [comment]
OK, with the same data I have the same result. 
I was using the task #4 results that I've uploaded in teams ('Cohort testing/Task #4 Third version o fthe package/Results/PreMerged.Rdata')

My guess is that the list of cohorts between those datasets and the cohorts.csv in the shiny app don't match, hence the issue I had.

**Comment by MaximMoinat** [comment]
I can confirm the issue is in the results file. Specifically, the `covariate` variable. So we should fix this in the study code. And maybe implement a quick fix to display the already collected results correctly in the shiny app.
![image](https://user-images.githubusercontent.com/17825660/121012313-e3c10900-c797-11eb-8673-e6352717d953.png)
