### ISSUE TITLE
Error while doing runStudy

### ISSUE THREAD

**Issue by rfherrerac** [ohdsi-studies/PioneerWatchfulWaiting#43]
After doing the cohort diagnostics, and then doing runStudy I got this error: 
Error: Can't subset columns that don't exist.
x Column `name` doesn't exist.

<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x Column `name` doesn't exist.
Backtrace:
     █
  1. └─PioneerWatchfulWaiting::runStudy(...)
  2.   └─PioneerWatchfulWaiting:::loadCohortsForExportFromPackage(cohortIds = counts$cohortId)
  3.     ├─base::rbind(cohorts, targetStrataXref[cols])
  4.     │ └─base::rbind(deparse.level, ...)
  5.     ├─targetStrataXref[cols]
  6.     ├─readr:::`[.spec_tbl_df`(targetStrataXref, cols)
  7.     ├─base::NextMethod(`[`)
  8.     └─tibble:::`[.tbl_df`(targetStrataXref, cols)
  9.       └─tibble:::vectbl_as_col_location(...)
 10.         ├─tibble:::subclass_col_index_errors(...)
 11.         │ └─base::withCallingHandlers(...)
 12.         └─vctrs::vec_as_location(j, n, names)
 13.           └─(function () ...
 14.             └─vctrs:::stop_subscript_oob(...)
 15.               └─vctrs:::stop_subscript(...)

**Comment by rfherrerac** [comment]
[PioneerWatchfulWaiting.txt](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/files/6662834/PioneerWatchfulWaiting.txt)

**Comment by marek05** [comment]
I got exactly the same error with the same error output on our dataset.

**Comment by MaximMoinat** [comment]
Thanks @rfherrerac and @marek05 for reporting. It seems to be a different part of the code than we previously looked at, same function `loadCohortsForExportFromPackage` though that throws the error.

I will be working on a fix.

**Comment by scossin** [comment]
I had the same error, I pulled the fix of @MaximMoinat and it worked !
