### ISSUE TITLE
Negative values in metrics distributions

### ISSUE THREAD

**Issue by bdemeulder** [ohdsi-studies/PioneerWatchfulWaiting#47]
As seen by Artem in shiny app
![shiny app issue metrics distribution18062021](https://user-images.githubusercontent.com/11734167/122580001-cae90b00-d055-11eb-8cc0-6fc8326d9d15.png)

This could be an error in how the number of days are substracted in the TimeToEvent or TimeToEventCombined SQL files?

**Comment by scossin** [comment]
@keesvanbochove @MaximMoinat @Tsemharb @bdemeulder 

I introduced this bug when mistranslating the DATEDIFF function that doesn't exist in Oracle: https://github.com/scossin/PioneerWatchfulWaiting/commit/5f3f4f5b1c85a05b0980866bd0a2e31034df10f9

```sql
SELECT DATEDIFF(day, '2016/10/19', '2021/04/25') AS DateDiff; -- returns 1649
```

```sql
SELECT ROUND(to_date('2016/10/19', 'YYYY/MM/DD') - to_date('2021/04/25', 'YYYY/MM/DD'), 0) as DateDiff
FROM DUAL -- returns -1649
```

It's my fault, we can close this issue.

**Comment by scossin** [comment]
I confirm the bug was only on my side, after the fix: https://github.com/scossin/PioneerWatchfulWaiting/commit/842f91c214f18419f0ddb7f40c68c0d3cdbbd1b4
It's much better

![FixDateDiff](https://user-images.githubusercontent.com/22571177/122596638-77cd8300-d06a-11eb-9ab4-8abf516318ab.png)
