### ISSUE TITLE
Shiny app time to event plot and table

### ISSUE THREAD

**Issue by bdemeulder** [ohdsi-studies/PioneerWatchfulWaiting#48]
When looking at time to event plots and table, the order of the outcomes in the plot and in the table is wrong when all plot choices are selected, but is right when a different number of plots is selected (from 1 to N-1). 

All selected: 
![shiny app time to event order of plots all selected 21062021](https://user-images.githubusercontent.com/11734167/122753536-b180d280-d292-11eb-9aec-d055829e27f1.png)

All but one: 
![shiny app time to event order of plots all but one selected  21062021](https://user-images.githubusercontent.com/11734167/122753547-b5acf000-d292-11eb-920c-2b9f8f82bc4d.png)

**Comment by keesvanbochove** [comment]
@bdemeulder this may be fixed by #71

**Comment by bdemeulder** [comment]
Confirm fixed.
