### ISSUE TITLE
Inclusion_4 (103.sql) - ORA-00955: name is already used by an existing object

### ISSUE THREAD

**Issue by scossin** [ohdsi-studies/PioneerWatchfulWaiting#62]
Peter reported this issue and I encountered it too: 
![peter_103_issue](https://user-images.githubusercontent.com/22571177/124307757-8dfa3980-db68-11eb-827b-9aaddafeaa0c.png)

According to Bertrand:
> Could it an easy fix that the second 4 should be changed to 5 and so on? (BTW, lines 483 and 533 in 103.sql).

**Comment by keesvanbochove** [comment]
This is a temporary table that should be dropped in the same script. Perhaps it is caused by an earlier script that was interrupted? For a new full run, you can DROP SCHEMA <your-cohort-schema> CASCADE (PostgreSQL syntax) and that should resolve this issue.
