### ISSUE TITLE
codemeta error in runStudy in episode branch

### ISSUE THREAD

**Issue by peterprinsen-iknl** [ohdsi-studies/PioneerWatchfulWaiting#65]
I get the following error in the runStudy function when I run the episode branch:

Warning: cannot open file 'C:/R/R-4.0.4/library/PioneerWatchfulWaiting/C:\Users\ppr2001.53019\OneDrive - IKNL\Pioneer\Studyathon 2021\project\output\NCR/codemeta.json': Invalid argument
Error in file(con, "w") : cannot open the connection

[PioneerWatchfulWaiting.txt](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/files/6786180/PioneerWatchfulWaiting.txt)

**Comment by keesvanbochove** [comment]
@peterprinsen-iknl this should be fixed in the newest version of the episode branch.
