### ISSUE TITLE
Error in runStudy

### ISSUE THREAD

**Issue by rfherrerac** [ohdsi-studies/PioneerWatchfulWaiting#66]
Backtrace:
 1. PioneerWatchfulWaiting::runStudy(...)
 2. PioneerWatchfulWaiting:::createBulkCharacteristics(...)
 3. DatabaseConnector::executeSql(connection = connection, sql = sql)
 4. base::tryCatch(...)
 5. base:::tryCatchList(expr, classes, parentenv, handlers)
 6. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7. value[[3L]](cond)
 8. DatabaseConnector:::.createErrorReport(...)
Run `rlang::last_trace()` to see the full context.
[errorReportSql.txt](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/files/6794831/errorReportSql.txt)

**Comment by rfherrerac** [comment]
<error/rlang_error>
Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "#" 
Position: 22;
An error report has been created at  /home/ronald/errorReportSql.txt
Backtrace:
 1. PioneerWatchfulWaiting::runStudy(...)
 2. PioneerWatchfulWaiting:::createBulkCharacteristics(...)
 3. DatabaseConnector::executeSql(connection = connection, sql = sql)
 4. base::tryCatch(...)
 5. base:::tryCatchList(expr, classes, parentenv, handlers)
 6. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7. value[[3L]](cond)
 8. DatabaseConnector:::.createErrorReport(...)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "#" 
Position: 22;
An error report has been created at  /home/ronald/errorReportSql.txt
Backtrace:
    █
 1. └─PioneerWatchfulWaiting::runStudy(...)
 2.   └─PioneerWatchfulWaiting:::createBulkCharacteristics(...)
 3.     └─DatabaseConnector::executeSql(connection = connection, sql = sql)
 4.       └─base::tryCatch(...)
 5.         └─base:::tryCatchList(expr, classes, parentenv, handlers)
 6.           └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7.             └─value[[3L]](cond)
 8.               └─DatabaseConnector:::.createErrorReport(...)

**Comment by rfherrerac** [comment]
Maybe it is in the BulkCharacerization.sql line 172. Extra space.

**Comment by bdemeulder** [comment]
Corrected the BulkFeatureExtraction.sql file.
