### ISSUE TITLE
addional issues in the results uploaded to the ShinyApp 

### ISSUE THREAD

**Issue by golozara** [ohdsi-studies/PioneerWatchfulWaiting#69]
Few additional issues based on reviewing the results:  

**1. we are missing the pre-index time window (-365 to -1 day).** We need to have this for description of the baseline characteristics. We have to check this. If this is not included in the package, we need to add that and send the updated version for execution 
2. The following target cohorts are missing: T2a, T4, T4a and T5
3. We have strata cohort 320 and 327. I believe these are already fixed but putting them here again as a reminder.

**Comment by MaximMoinat** [comment]
As discussed in meeting on July 29th.
Point 2: No cohort counts in the results for cohorts T2a, T4, T4a and T5. These are not exported to the results file and therefore these cohorts do not show up in the shiny app.

Point 3: strata 320 and 327 have commas in their concept name. These will be removed.

**Comment by keesvanbochove** [comment]
Actually I believe the real issue was that strata 320 and 327 had a misplaced comma and was fixed before (see https://github.com/ohdsi-studies/PioneerWatchfulWaiting/commit/e84135dc6135992a9014a2affab9ddd572d5b82a) but it probably can't hurt to remove the commas completely.

**Comment by keesvanbochove** [comment]
So all these issues should be resolved in the latest master version @golozara - any way you can test this in a database where you did see at least some matching patients in any of those cohorts (for issue number 2 above)?
