### ISSUE TITLE
Issue with runstudy function (fread_csv)

### ISSUE THREAD

**Issue by marek05** [ohdsi-studies/PioneerWatchfulWaiting#77]
I run the version v0.4.3 and encountered an issue with a function:

        Error: 'fread_csv' is not an exported object from 'namespace:data.table'

The issue is with this line and I think there should be "fread" not "fread_csv" 
https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/366c4cfa602cc73b7474e8424c1edd72ba0de259/R/RunStudy.R#L383

**Comment by keesvanbochove** [comment]
@marek05 thanks for reporting that, could you try again with the current master branch version?

**Comment by marek05** [comment]
Thanks. master branch is working correctly. I could run the package successfully.
