### ISSUE TITLE
Issue with cohort PIONEER T3.2a

### ISSUE THREAD

**Issue by marek05** [ohdsi-studies/PioneerWatchfulWaiting#80]
In cohort "[PIONEER T3.2a] PCa low risk grade conservative management and no intense monitoring broad" (cohortId=108) there is a issue with missing concept sets.
I think there shouldn't be "Any Measurement" and "Any Observation" but instead PSA concept sets like in  In cohort PIONEER T3.2 (cohortId=107).
  
![pilt](https://user-images.githubusercontent.com/5746002/131839080-00810aee-ac05-4da9-81df-a7466c3bd6d2.png)

Although changing it doesn't affect results for Estonian dataset (still 0).

**Comment by keesvanbochove** [comment]
Good catch @marek05! Asieh also noticed this cohort was empty in all databases. I have updated the definition in ATLAS and also pulled this into the master branch: https://github.com/ohdsi-studies/PioneerWatchfulWaiting/commit/423661b6b55168f33dcb954e2698dde79bb39870
