### ISSUE TITLE
Negative time to event values for 3 target cohorts

### ISSUE THREAD

**Issue by keesvanbochove** [ohdsi-studies/PioneerWatchfulWaiting#84]
The current time to event generation feature (which fits a survival curve over several combinations of target/strata cohorts vs outcome cohorts) generates up to -180 days negative values in 3 cohorts (and their strata permutations):
* [PIONEER T2] PCa treated right away
* [PIONEER T3] PCa under conservative management
* [PIONEER T3a] PCa under conservative management_broad

It seems that the outcomes fed to the model occur *before* the index event in these target cohorts.

**Comment by keesvanbochove** [comment]
<img width="1408" alt="problem" src="https://user-images.githubusercontent.com/373418/133421584-5e0840d6-5e39-43aa-ba56-98544748c1d2.PNG">
As visible in this screenshot, these cohorts (T2 in this case) sometimes seem to generate entries where the end date is before the start date. Combined with the fact that TimeToEvent.sql takes the max of the target cohort end dates in cases where there is no matching outcome cohort, this leads to the negative time to event values. So we need to debug these cohort definitions.

**Comment by MaximMoinat** [comment]
Issue is in adding a fixed amount of days (180 or 548) to the cohort `start_date`. The cohort `end_date` could be within those days.

https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/8e40ba3525109c01ea429df1d6e888b67388b864/inst/sql/sql_server/104.sql#L1196

**Comment by MaximMoinat** [comment]
The proposed fix in #86 will remove persons that might be eligible. In case a person has a censoring event (e.g. malignancy) before the offset index date, then this person will have a cohort_end before it. But only after this offset index date it should run.

The `DATEADD` should be here:
https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/081d70955c318074cb470615b2cc36cb7e93a7f7/inst/sql/sql_server/103.sql#L215-L216

**Comment by keesvanbochove** [comment]
See discussion under #86 and #87, for now have added in the fix from #86.
