### ISSUE TITLE
Error when sending to the OHDSI server

### ISSUE THREAD

**Issue by rfherrerac** [ohdsi-studies/PioneerWatchfulWaiting#9]
After running: 
library("OhdsiSharing")
privateKeyFileName <- "~/Characterization/study-data-site-pioneer"
userName <- "study-data-site-pioneer"
fileName <- "/home/ronald/Characterization/CPRD/diagnostics/Results_diagnostics_CPRD.zip"
folderName <- "CPRD"
sftpUploadFile(privateKeyFileName, userName, folderName, fileName)

Got: 

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.FileNotFoundException: ~/CharacD5/CPRDD5/Results_CPRDD5.zip (No such file or directory)

And the file is actually there.

**Comment by keesvanbochove** [comment]
Hi @rfherrerac, the file not found exception mentions a different file and path than the fileName you assigned above it. Could you double check your variable assignments? The [sftpUploadFile](https://github.com/OHDSI/OhdsiSharing/blob/8778421042e74e8824c00a58cf63bedfbfeb54aa/R/Sftp.R#L231) function just uploads one file to the remote folder, and it should be generating a log message "Uploading ..." - can you check the log as well?

**Comment by keesvanbochove** [comment]
Fixed by updating upload functions in Sharing.R.
