### ISSUE TITLE
Shiny app v0.4.4 - legend in time to event

### ISSUE THREAD

**Issue by bdemeulder** [ohdsi-studies/PioneerWatchfulWaiting#90]
The colors in the time to event analysis don't match between the figure and the table below. 

![Shiny app 04102021 - time to event](https://user-images.githubusercontent.com/11734167/135839805-3cf1265e-9825-4dd8-8d02-cada78d6535a.png)

**Comment by thulsen** [comment]
Proposed solution is at https://github.com/OHDSI/ShinyDeploy/pull/141
