### ISSUE TITLE
Error in Cohort Characterization tab

### ISSUE THREAD

**Issue by bdemeulder** [ohdsi-studies/PioneerWatchfulWaiting#94]
In the shiny app cohort characterisation, there seems to be an error in parsing the results. 
![image](https://user-images.githubusercontent.com/11734167/137880157-60c06876-df5c-4bf7-9e70-17a35d10be43.png)

Further, when looking only at the demographics domain, it seems the rows are replicated many times in the table (e.g. more than 170 occurences of gender=male)

![image](https://user-images.githubusercontent.com/11734167/137880753-c78249cf-7b1a-459e-93cb-97cda3695a9c.png)

Compare cohorts characteristics seems fine.

**Comment by keesvanbochove** [comment]
> The version of the results viewer on https://data.ohdsi.org/PioneerWatchfulWaiting/ still has this issue. The download button on the characterization tab fails as well.
> 
@bdemeulder could you upload the new merged set to the OHDSI server so this could be fixed online as well?

**Comment by bdemeulder** [comment]
@keesvanbochove , I've updated the merged set and created a pull request on shiny deploy to trigger the update. Could you approve it?

**Comment by ahijazy** [comment]
Facing the same issue, could you please clarify how was the error finally solved?
